---
kind: pipeline
type: docker
name: Production pipeline

steps:
  - name: publish image to production
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_production
      secret_key:
        from_secret: aws_access_key_secret_production
      region: eu-west-1
      repo:   cust-production-bpc-ecr/bpc_console
      registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: Dockerfile
      tags:
        - latest
        - ${CI_COMMIT_SHA}

  - name: Deploy to production
    image: pelotech/drone-ecs:1.0.7
    environment:
      BPC_APP_SECRET:
        from_secret: bpc_app_secret_production
      BPC_APP_ID:
        from_secret: bpc_app_id_production
    settings:
      secret_environment_variables:
        - BPC_APP_SECRET
        - BPC_APP_ID      
      aws_access_key_id:
        from_secret: aws_access_key_production
      aws_secret_access_key:
        from_secret: aws_access_key_secret_production
      cluster: cust-production-bpc
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-production-bpc-ecr/bpc_console
      container_name: cust-production-bpc-bpc_console-container
      family: cust-production-bpc-bpc_console
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-production-bpc
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=cust-production-bpc-bpc_console
      memory: 512
      port_mappings:
        - 8100 8000
      region: eu-west-1
      service: cust-production-bpc-bpc_console
      service_network_security_groups:
      [security_groups]
      service_network_subnets:
      [subnets]
      tag: ${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-production-bpc-bpc_console-exec
      task_memory: 512
      task_network_mode: awsvpc

trigger:
  repo:
    - BerlingskeMedia/bpc_console
  branch:
    - master
  event:
    include:
      - push
    exclude:
      - pull_request

---
kind: pipeline
type: docker
name: Staging pipeline

steps:
  - name: publish image to staging
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_production
      secret_key:
        from_secret: aws_access_key_secret_production
      region: eu-west-1
      repo:   cust-production-bpc-ecr/bpc_console
      registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: Dockerfile
      tags:
        - latest
        - ${CI_COMMIT_SHA}

  - name: Deploy to staging
    image: pelotech/drone-ecs:1.0.7
    environment:
      BPC_APP_SECRET:
        from_secret: bpc_app_secret_staging
      BPC_APP_ID:
        from_secret: bpc_app_id_staging
      settings:
        secret_environment_variables:
          - BPC_APP_SECRET
          - BPC_APP_ID
      aws_access_key_id:
        from_secret: aws_access_key_production
      aws_secret_access_key:
        from_secret: aws_access_key_secret_production
      cluster: cust-production-bpc
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-production-bpc-ecr/bpc_console
      container_name: cust-production-bpc-bpc_console-container
      family: cust-production-bpc-bpc_console
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-production-bpc
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=cust-production-bpc-bpc_console
      memory: 512
      port_mappings:
        - 8100 8000
      region: eu-west-1
      service: cust-production-bpc-bpc_console
      service_network_security_groups:
      [security_groups]
      service_network_subnets:
      [subnets]
      tag: ${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-production-bpc-bpc_console-exec
      task_memory: 512
      task_network_mode: awsvpc

trigger:
  repo:
    - BerlingskeMedia/bpc_console
  branch:
    - master
  event:
    include:
      - push
    exclude:
      - pull_request

---
kind: pipeline
type: docker
name: test pipeline

steps:
  - name: publish image to test
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_testing
      secret_key:
        from_secret: aws_access_key_secret_testing
      region: eu-west-1
      repo:   cust-production-bpc-ecr/bpc_console
      registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
      dockerfile: Dockerfile
      tags:
        - ${DRONE_TAG}-${CI_COMMIT_SHA}
        - ${CI_COMMIT_SHA}

  - name: Deploy to test QA1
    image: pelotech/drone-ecs:1.0.7
    environment:
      BPC_APP_SECRET:
        from_secret: bpc_app_secret_testing
      BPC_APP_ID:
        from_secret: bpc_app_id_testing
      settings:
        secret_environment_variables:
          - BPC_APP_SECRET
          - BPC_APP_ID
      aws_access_key_id:
        from_secret: aws_access_key_testing
      aws_secret_access_key:
        from_secret: aws_access_key_secret_testing
      cluster: cust-production-bpc
      compatibilities: FARGATE
      deployment_configuration: 100 200
      desired_count: 1
      docker_image: 815296035528.dkr.ecr.eu-west-1.amazonaws.com/cust-production-bpc-ecr/bpc_console
      container_name: cust-production-bpc-bpc_console-container
      family: cust-production-bpc-bpc_console
      log_driver: awslogs
      log_options:
        - awslogs-group=cust-production-bpc
        - awslogs-region=eu-west-1
        - awslogs-stream-prefix=cust-production-bpc-bpc_console
      memory: 512
      port_mappings:
        - 8100 8000
      region: eu-west-1
      service: cust-production-bpc-bpc_console
      service_network_security_groups:
      [security_groups]
      service_network_subnets:
      [subnets]
      tag: ${CI_COMMIT_SHA}
      task_cpu: 256
      task_execution_role_arn: arn:aws:iam::815296035528:role/cust-production-bpc-bpc_console-exec
      task_memory: 512
      task_network_mode: awsvpc
    when:
      ref:
        include:
          - refs/tags/qa1*
        exclude:
          - refs/heads/master

trigger:
  repo:
    - BerlingskeMedia/bpc_console
  event:
    - tag
  ref:
    include:
      - refs/tags/qa*
---
kind: "secret"
name: "aws_access_key_testing"
get:
  path: "drone/cust-testing-bpc"
  name: "aws_access_key"
---
kind: "secret"
name: "aws_access_key_secret_testing"
get:
  path: "drone/cust-testing-bpc"
  name: "aws_access_key_secret"
---
kind: "secret"
name: "aws_access_key_production"
get:
  path: "drone/cust-production-bpc"
  name: "aws_access_key"
---
kind: "secret"
name: "aws_access_key_secret_production"
get:
  path: "drone/cust-production-bpc"
  name: "aws_access_key_secret"
---
kind: "secret"
name: "aws_access_key_staging"
get:
  path: "drone/cust-staging-bpc"
  name: "aws_access_key"
---
kind: "secret"
name: "aws_access_key_secret_staging"
get:
  path: "drone/cust-staging-bpc"
  name: "aws_access_key_secret"
